### ISSUE TITLE
Stitch grids with empty columns or rows

### ISSUE THREAD

**Issue by ibordeu** [VasylVaskivskyi/biostitch#9]
Hi,
I am using the code to stitch two sets of images, I have no problem with the first set (grid attached, sample1.jpg)

![sample1](https://user-images.githubusercontent.com/10849196/82343426-bcf82f00-99ea-11ea-9ecd-f08b24f3ddc6.jpg)

However, I run into the following error when attempting to stitch the second sample (grid attached, sample2.jpg):

![sample2](https://user-images.githubusercontent.com/10849196/82343442-c2557980-99ea-11ea-94ec-5fedcf522b34.jpg)

**started at 2020-05-19 15:05:19.059629
plane 1/200Traceback (most recent call last):
  File "/Users/user/anaconda3/envs/biostitch/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/user/anaconda3/envs/biostitch/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/user/Documents/biostitch-master/biostitch/__main__.py", line 64, in <module>
    main()
  File "/Users/user/Documents/biostitch-master/biostitch/__main__.py", line 60, in main
    stitcher.stitch()
  File "/Users/user/Documents/biostitch-master/biostitch/stitcher.py", line 61, in stitch
    self.perform_stitching(ids, x_size, y_size, plane_path_list, field_path_list, self._ome_meta)
  File "/Users/user/Documents/biostitch-master/biostitch/stitcher.py", line 237, in perform_stitching
    TW.save(stitch_plane(plane, ids, x_size, y_size, self._y_pos, self._ill_cor_ch[channel], self._scan),
  File "/Users/user/Documents/biostitch-master/biostitch/image_processing.py", line 190, in stitch_plane
    result_plane[0, :, :] = stitch_images(images, ids, x_size, y_size, y_pos, scan_mode)
  File "/Users/user/Documents/biostitch-master/biostitch/image_processing.py", line 175, in stitch_images
    crop_images_scan_manual(images, ids.iloc[row, :], x_size.iloc[row, :], y_size.iloc[row, :]), axis=1)
ValueError: could not broadcast input array from shape (1059,6395) into shape (1059,7431)**

It seems to me like the error occurs due to the empty column between blocks 1 and 6 (see grid in sample2), where no images were acquired.

Any help in solving this issue would be amazing.

**Comment by VasylVaskivskyi** [comment]
Hi @ibordeu,
Could you please submit a small example of the data with gap between columns?

**Comment by ibordeu** [comment]
Hi @VasylVaskivskyi 
You can download a sample data from 
https://www.dropbox.com/t/n26ItOQq3rGKYP8v
(I will disable the link once you have downloaded the data)
This folder contains the Index.idx.xml file plus 26 images, which correspond to the first two z-planes of imaging (13 images per plane).
The channel is DAPI.

**Comment by VasylVaskivskyi** [comment]
@ibordeu thank you, you can remove the link

**Comment by ibordeu** [comment]
@VasylVaskivskyi Ok, thanks.

**Comment by VasylVaskivskyi** [comment]
Fixed
ab0c2194e81369b987b2119944b541ee5e7ecbf8

**Comment by ibordeu** [comment]
I just tested it on the full data set. It works perfectly, thanks!
